### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [adorsys/ledgers#1]
Hi
The following lines have cryptographic API misuses. <br> File name => ledgers-utils/src/main/java/de/adorsys/ledgers/util/MD5Util.java: Line number => 30: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => ledgers-utils/src/main/java/de/adorsys/ledgers/util/MD5Util.java: Line number => 32: API name => MessageDigest:<BR>

**Comment by jfractalus** [comment]
Hi. There is no MD5Util.java in ledgers-utils/src/main/java/de/adorsys/ledgers/util/. Which version of Ledgers are you using?
