### ISSUE TITLE
field isValid should be valid in the de.adorsys.ledgers.middleware.api.domain.um.ScaUserDataTO

### ISSUE THREAD

**Issue by djole87** [adorsys/ledgers#3]
After successfully executed start of the authorization, execution of following API call 

> PUT /v1/consents/{consentId}/authorisations/{authorisationId} Update PSU data for consents
with request body param: 
```
{
	"psuData": {
		"password": "12345"
	}
}
```

fails with the following exception: 
`Error while extracting response for type [class de.adorsys.ledgers.middleware.api.domain.sca.SCALoginResponseTO] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized field "valid" (class de.adorsys.ledgers.middleware.api.domain.um.ScaUserDataTO), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "valid" (class de.adorsys.ledgers.middleware.api.domain.um.ScaUserDataTO), not marked as ignorable (7 known properties: "methodValue", "scaMethod", "staticTan", "usesStaticTan", "id", "decoupled", "user"])`

Maybe field `valid` should be added the same way field `decoupled` is added, so with proper `isValid()` get method.

**Comment by jfractalus** [comment]
Hi, Djordje . Now we are preparing new release of Ledgers with this fix.
Thank you!

чт, 30 янв. 2020 г. в 15:42, Djordje Stanojevic <notifications@github.com>:

**Comment by djole87** [comment]
Hi Petro,

Following API calls still cannot be executed:

> PUT /v1/{payment-service}/{payment-product}/{paymentId}/authorisations/{authorisationId}
with request body param:

```
{
	"psuData": {
		"password": "12345"
	}
}
```
 
and with request body

```
{
		"scaAuthenticationData": "{tan_value}"
}
```

Maybe some props needs to be ignored during deserialization like `valid` from class `ScaUserDataTO` and `authConfirmationCode` from class `ScaResponseTO`.

Payment in Embedded SCA approach cannot be successfully executed without these calls.

**Comment by jfractalus** [comment]
Hi, Djordje. The new release of Ledgers 2.8 with this fix will be available today. I will let you know as soon as it appears

**Comment by jfractalus** [comment]
Hi again, Ledgers 2.8 was released. Please try one more time

**Comment by djole87** [comment]
Now it works. Thanks!
I will close this issue.
