### ISSUE TITLE
Online banking app - Redirect SCA approach problem

### ISSUE THREAD

**Issue by djole87** [adorsys/ledgers#4]
Hi Petro,
It seems that there is another similar issue, please find details below
After following scaRedirect URL the following exception is thrown:

![image](https://user-images.githubusercontent.com/8372413/74161929-1ac4f000-4c20-11ea-892e-989e43b68e9a.png)

I've posted it here as well 
https://github.com/adorsys/XS2A-Sandbox/issues/12

**Comment by jfractalus** [comment]
Hi, Djordje. I saw your message. It seems you are using outdated versions. The latest version is:
Ledgers v.2.8
XS2A v.5.9
ASPSP-Profile v.5.9
Consent-Management v.5.9
XS2A Connector-Examples v.5.9

**Comment by djole87** [comment]
I'm using the latest Sandbox.
Here is output from my docker ps -a command

![image](https://user-images.githubusercontent.com/8372413/74230585-fa9b3c80-4cc4-11ea-9af3-1fb6dfadcc9a.png)

Please let me know if I need to update something

**Comment by jfractalus** [comment]
I would suggest to remove all Docker images (with volumes) and start from scratch.
To delete all containers including its volumes use,
docker rm -vf $(docker ps -a -q)
To delete all the images,
docker rmi -f $(docker images -a -q)
Remember, you should remove all the containers before removing all the images from which those containers were created.
docker volume rm $(docker volume ls -q)

**Comment by djole87** [comment]
Outdated Images were the problem, thanks.
Anyhow, after successful consent creation in Redirect SCA approach, user max.muserman is not able to log in

![image](https://user-images.githubusercontent.com/8372413/74233966-0e966c80-4ccc-11ea-82ce-4b55492fef05.png)

**Comment by jfractalus** [comment]
Please set spring profile 'develop' in Ledgers

**Comment by djole87** [comment]
now it works thanks
